### ISSUE TITLE
Implement Dependency Tracking

### ISSUE THREAD

**Issue by DavePearce** [DavePearce/EvmIL#73]
_(see also #72)_

The aim here is to alter the way that a `Disassembly` is calculated, such that we can identify where in the bytecode sequence a particular constant comes from.  Necessary changes:

- [x] Provide a set concept which can be used to aggregate concrete values.
- [x] Add failing tests to illustrate the problem
- [ ] Provide mechanism for a `Stepper` to store the `pc` value with the value being pushed.

**Comment by DavePearce** [comment]
_How does this help us, and what does it achieve?_

**Comment by DavePearce** [comment]
I think the easiest way forward for me is to close this issue by enabling the abstract stepper to enumerate available jump destinations.  Subsequently, we can open a separate issue to resolve information flow problems (e.g. that the returned stack may be to short, etc).
